/** @file
 * Copyright (c) 2026, Arm Limited or its affiliates. All rights reserved.
 * SPDX-License-Identifier : Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **/

#include "acs_val.h"
#include "acs_pe.h"
#include "acs_mpam.h"
#include "acs_mpam_reg.h"
#include "acs_gic.h"
#include "val_interface.h"

/*
 * Algorithm:
 * 1. Iterate all MSC nodes and filter out those missing required features.
 * 2. For each eligible MSC, program ERR_MSI and provoke an out-of-range MON_SEL.
 * 3. Wait for the MSI, validate handler invocation and expected errcode.
 * 4. Restore registers and disable ERR_MSI before moving to the next MSC.
 */

#define TEST_NUM   ACS_MPAM_ERROR_TEST_NUM_BASE  +  20
#define TEST_DESC  "Check MPAM error MSI interrupt status "
#define TEST_RULE  ""

static uint32_t msc_index;
static uint32_t msi_intr_num = 0x204C;
static volatile uint32_t handler_invoked;
static volatile uint32_t errcode_valid;
static volatile uint32_t mon_sel_not_updated;
static uint32_t max_ris_index;
static uint32_t msmon_cfg_mon_sel_saved;

/* Disable ERR_MSI for the given MSC index. */
static void
mpam_disable_err_msi(uint32_t msc_idx)
{
    val_mpam_mmr_write(msc_idx, REG_MPAMF_ERR_MSI_ATTR, 0);
}

static
void intr_handler(void)
{
    uint32_t pe_index = val_pe_get_index_mpid(val_pe_get_mpid());
    uint32_t errcode;
    uint32_t data;

    val_print(ACS_PRINT_DEBUG, "\n       MSC Index %d Handler Code", msc_index);

    /* Mark handler entry for timeout/flow checks. */
    handler_invoked = 1;

    /* Check whether MON_SEL update was accepted by the MSC. */
    max_ris_index = val_mpam_get_max_ris_count(msc_index) + 1;
    data = val_mpam_mmr_read(msc_index, REG_MSMON_CFG_MON_SEL);

    /* If MON_SEL is not updated and updating mon_sel raised the error */
    if (((data >> MON_SEL_RIS_SHIFT) & MON_SEL_RIS_MASK) != (max_ris_index + 1)) {
      mon_sel_not_updated = 1;
    }

    /* Validate the error code generated by the MSC. */
    errcode = val_mpam_msc_get_errcode(msc_index);
    if (errcode != ESR_ERRCODE_UNDEF_RIS_MON_SEL) {
        val_print(ACS_PRINT_ERR,
            "\n       Expected errcode: %d", ESR_ERRCODE_UNDEF_RIS_MON_SEL);
        val_print(ACS_PRINT_ERR,
            "\n       Actual errcode: %d", errcode);
        val_set_status(pe_index, RESULT_FAIL(TEST_NUM, 02));
    } else {
        errcode_valid = 1;
        val_set_status(pe_index, RESULT_PASS(TEST_NUM, 01));
    }

    /* Stop further ERR_MSI assertions once handled */
    mpam_disable_err_msi(msc_index);
    val_mpam_memory_mbwumon_disable(msc_index);

    /* Clear the error for the next iteration. */
    val_mpam_msc_reset_errcode(msc_index);
}

static
void payload(void)
{
    uint32_t pe_index    = val_pe_get_index_mpid(val_pe_get_mpid());
    uint32_t total_nodes = val_mpam_get_msc_count();
    uint32_t status;
    uint32_t test_fail = 0;
    uint32_t test_skip = 1;
    uint32_t handler_installed;
    uint32_t mpamf_ecr;
    uint32_t data;
    uint32_t device_id = 0;
    uint32_t its_id = 0;
    uint64_t timeout;
    uint64_t mpamf_idr;


    for (msc_index = 0; msc_index < total_nodes; msc_index++) {
        handler_installed = 0;
        device_id = 0;
        its_id = 0;

        /* Skip MSCs without ESR support. */
        if (!val_mpam_msc_supports_esr(msc_index)) {
            val_print(ACS_PRINT_DEBUG,
                "\n       MSC %d doesn't support ESR, skipping MSC", msc_index);
            continue;
        }

        /* Skip MSCs without RIS support. */
        if (!val_mpam_msc_supports_ris(msc_index)) {
            val_print(ACS_PRINT_DEBUG,
                "\n       MSC %d doesn't support RIS, skipping MSC", msc_index);
            continue;
        }

        /* Skip MSCs without MON support. */
        if (!val_mpam_msc_supports_mon(msc_index)) {
            val_print(ACS_PRINT_DEBUG,
                "\n       MSC %d doesn't support MON, skipping MSC", msc_index);
            continue;
        }

        mpamf_idr = val_mpam_mmr_read64(msc_index, REG_MPAMF_IDR);
        /* Skip MSCs without ERR_MSI support. */
        if (!BITFIELD_READ(IDR_HAS_ERR_MSI, mpamf_idr)) {
            val_print(ACS_PRINT_DEBUG,
                "\n       MSC %d doesn't support ERR_MSI, skipping MSC", msc_index);
            continue;
        }

        /* Resolve device and ITS IDs for MSI programming. */
        status = val_mpam_get_msc_device_info(msc_index, &device_id, &its_id);
        if (status) {
            val_print(ACS_PRINT_ERR,
                "\n       Could not get device & ITS info for MSC %d", msc_index);
            test_fail++;
            break;
        }

        /* Install the ISR once per MSC loop, then route the interrupt. */
        if (!handler_installed) {
            status = val_gic_install_isr(msi_intr_num, intr_handler);
            if (status) {
                val_print(ACS_PRINT_ERR,
                    "\n       Failed to install ISR for interrupt %d", msi_intr_num);
                test_fail++;
                break;
            }

            val_gic_route_interrupt_to_pe(msi_intr_num, val_pe_get_mpid_index(pe_index));
            handler_installed = 1;
        }

        /* Assign the MSI to the MSC. */
        status = val_mpam_msc_request_msi(msc_index, device_id, its_id, msi_intr_num, 0);
        if (status) {
            val_print(ACS_PRINT_ERR,
                "\n       MSI Assignment failed for MSC %d", msc_index);
            test_fail++;
            break;
        }

        /* Read MPAMF_ECR before generating error. This will be used to restore to default later */
        mpamf_ecr = val_mpam_mmr_read(msc_index, REG_MPAMF_ECR);
        /* Ensure a clean error state before injecting a new error. */
        status = val_mpam_msc_reset_errcode(msc_index);
        if (!status) {
            val_set_status(pe_index, RESULT_FAIL(TEST_NUM, 01));
            test_fail++;
            break;
        }

        /* Start test sequence for this MSC. */
        test_skip = 0;
        handler_invoked = 0;
        mon_sel_not_updated = 0;
        errcode_valid = 0;
        val_set_status(pe_index, RESULT_PENDING(TEST_NUM));

        /* Save MSMON_CFG_MON_SEL for restoration. */
        msmon_cfg_mon_sel_saved = val_mpam_mmr_read(msc_index, REG_MSMON_CFG_MON_SEL);

        /* Enable ERR_MSI to capture the injected error. */
        status = val_mpam_msc_enable_msi(msc_index, 0);
        if (status) {
            val_print(ACS_PRINT_ERR,
                "\n       Failed to enable ERR_MSI for MSC %d", msc_index);
            test_fail++;
            goto msc_cleanup;
        }

        /* Program MSMON_CFG_MON_SEL with out-of-range RIS index */
        max_ris_index = val_mpam_get_max_ris_count(msc_index);
        data = BITFIELD_SET(MON_SEL_MON_SEL, 0) |
               BITFIELD_SET(MON_SEL_RIS, (max_ris_index + 1));
        val_mpam_mmr_write(msc_index, REG_MSMON_CFG_MON_SEL, data);

        /* If MON_SEL is not updated then accessing the register will result into error */
        if (!mon_sel_not_updated) {
          /* Access MSMON_CFG_* register to cause the error */
          val_mpam_mmr_read(msc_index, REG_MSMON_CFG_MON_SEL);
        }

        /* Wait for handler to update status, or timeout. */
        timeout = TIMEOUT_LARGE;
        while ((--timeout > 0) && (IS_RESULT_PENDING(val_get_status(pe_index))));

        if (timeout == 0) {
            val_print(ACS_PRINT_ERR,
                "\n       Error MSI not received for MSC %d", msc_index);
            test_fail++;
            goto msc_cleanup;
        }

        if (!handler_invoked) {
            val_print(ACS_PRINT_ERR,
                "\n       Handler not invoked for MSC %d after error", msc_index);
            test_fail++;
            goto msc_cleanup;
        }

        if (!errcode_valid) {
            val_print(ACS_PRINT_ERR,
                "\n       Expected errcode not observed for MSC %d", msc_index);
            test_fail++;
            goto msc_cleanup;
        }

    msc_cleanup:
        /* Restore state before moving to the next MSC. */
        val_mpam_mmr_write(msc_index, REG_MSMON_CFG_MON_SEL, msmon_cfg_mon_sel_saved);
        val_mpam_mmr_write(msc_index, REG_MPAMF_ECR, mpamf_ecr);
        val_mpam_msc_reset_errcode(msc_index);
        mpam_disable_err_msi(msc_index);

        if (test_fail)
            break;
    }

    if (test_skip)
        val_set_status(pe_index, RESULT_SKIP(TEST_NUM, 01));
    else if (test_fail)
        val_set_status(pe_index, RESULT_FAIL(TEST_NUM, 02));
    else
        val_set_status(pe_index, RESULT_PASS(TEST_NUM, 01));
}

uint32_t intr006_entry(void)
{
    uint32_t status  = ACS_STATUS_FAIL;
    uint32_t num_pe  = 1;

    /* Standard ACS test entry/exit flow. */
    status = val_initialize_test(TEST_NUM, TEST_DESC, num_pe);

    if (status != ACS_STATUS_SKIP)
        val_run_test_payload(TEST_NUM, num_pe, payload, 0);

    status = val_check_for_error(TEST_NUM, num_pe, TEST_RULE);
    val_report_status(0, ACS_END(TEST_NUM), TEST_RULE);

    return status;
}
